---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['USER'] %>
  instance_type: m3.medium

provisioner:
  name: salt_solo
  formula: salt
  pillars-from-files:
    salt.sls: test/fixtures/pillar.yml
  pillars:
    top.sls:
      base:
        '*':
          - salt

transport:
  ssh_key: ~/.ssh/id_rsa

verifier:
  name: inspec
  format: doc

platforms:
  - name: amazon
    driver:
      image_id: ami-f3559b9e
    transport:
      username: ec2-user
  - name: ubuntu
    driver:
      image_id: ami-c45a94a9
    transport:
      username: ubuntu

suites:
  - name: minion
    provisioner:
      state_top:
        base:
          '*':
            - salt
  - name: master
    provisioner:
      state_top:
        base:
          '*':
            - salt
            - salt.master
            - salt.api
